### PR TITLE
eliminate spurious metadb-related syncs

### LINKED ISSUE #880: eliminate spurious metadb-related syncs
Currently, when running `pgbench`, we see four `zfs_fsync` calls on every flush and two on every write.  Most of these syncs are due to metadb activity:

```console
# dtrace -n zfs_fsync:entry'/pid == $target/{@[ustack()] = count()}' -p `pgrep -nf downstairs`
...
              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x7d48
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::Connection::execute_batch::h2bd30115d9e1ee0c+0xad
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_write::{{closure}}::hc233a80def2b212d+0x1df2
              crucible-downstairs-stock`crucible_downstairs::Downstairs::do_work::{{closure}}::h3573ac87781d5210+0x2b32
              crucible-downstairs-stock`crucible_downstairs::resp_loop::{{closure}}::{{closure}}::h37c33435bf7df50f+0xead
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h2c0e4f7a0e1c47b9+0x3a
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::h3ee92d2e048a9d64+0x2c
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h6694c00f9919cbef+0x4f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x146
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
              400

              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x9ef4
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::statement::Statement::execute_with_bound_parameters::ha3394ff9a5a5f4f7+0x20
              crucible-downstairs-stock`crucible_downstairs::region::Inner::set_dirty::h5d67f9776c4e1ff7+0xd3
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_write::{{closure}}::hc233a80def2b212d+0x1900
              crucible-downstairs-stock`crucible_downstairs::Downstairs::do_work::{{closure}}::h3573ac87781d5210+0x2b32
              crucible-downstairs-stock`crucible_downstairs::resp_loop::{{closure}}::{{closure}}::h37c33435bf7df50f+0xead
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h2c0e4f7a0e1c47b9+0x3a
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::h3ee92d2e048a9d64+0x2c
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h6694c00f9919cbef+0x4f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
            27377

              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x7d48
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::Connection::execute_batch::h2bd30115d9e1ee0c+0xad
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_write::{{closure}}::hc233a80def2b212d+0x1df2
              crucible-downstairs-stock`crucible_downstairs::Downstairs::do_work::{{closure}}::h3573ac87781d5210+0x2b32
              crucible-downstairs-stock`crucible_downstairs::resp_loop::{{closure}}::{{closure}}::h37c33435bf7df50f+0xead
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h2c0e4f7a0e1c47b9+0x3a
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::h3ee92d2e048a9d64+0x2c
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h6694c00f9919cbef+0x4f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
            27500

              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x7d48
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::Connection::execute_batch::h2bd30115d9e1ee0c+0xad
              crucible-downstairs-stock`crucible_downstairs::region::Inner::truncate_encryption_contexts_and_hashes::h26ba761c5edfce6f+0x2a1
              crucible-downstairs-stock`crucible_downstairs::region::Extent::flush::{{closure}}::hef5a6a42edc99711+0xd6f
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_flush::{{closure}}::{{closure}}::{{closure}}::hee73657bd4698756+0x9a
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h4896c8105e86516c+0x42
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::hfd96b7233ec469b1+0x2d
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h9f28b8cbe09a5416+0x56
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
            27710

              libc.so.1`__fdsync+0xa
              crucible-downstairs-stock`std::fs::File::sync_all::h7ea020a119916743+0x15
              crucible-downstairs-stock`crucible_downstairs::region::Extent::flush::{{closure}}::hef5a6a42edc99711+0x810
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_flush::{{closure}}::{{closure}}::{{closure}}::hee73657bd4698756+0x9a
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h4896c8105e86516c+0x42
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::hfd96b7233ec469b1+0x2d
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h9f28b8cbe09a5416+0x56
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h70b6512986a3881f+0x8e
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::h5278e1de91a17ea8+0x2b
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h88f48d2e69032cac+0x9b
              crucible-downstairs-stock`tokio::runtime::blocking::pool::Inner::run::hb665b6d0101add85+0xef
              crucible-downstairs-stock`std::sys_common::backtrace::__rust_begin_short_backtrace::h30888fa5aefe33f0+0x73
              crucible-downstairs-stock`core::ops::function::FnOnce::call_once{{vtable.shim}}::h5757cbb2b9e71a3f+0xa3
              crucible-downstairs-stock`std::sys::unix::thread::Thread::new::thread_start::h0604336de98f7b8b+0x29
              libc.so.1`_thrp_setup+0x77
            27717

              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x9ef4
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::statement::Statement::execute_with_bound_parameters::ha3394ff9a5a5f4f7+0x20
              crucible-downstairs-stock`crucible_downstairs::region::Inner::set_flush_number::h8b5da2ebc784c069+0x125
              crucible-downstairs-stock`crucible_downstairs::region::Extent::flush::{{closure}}::hef5a6a42edc99711+0xe0b
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_flush::{{closure}}::{{closure}}::{{closure}}::hee73657bd4698756+0x9a
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h4896c8105e86516c+0x42
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::hfd96b7233ec469b1+0x2d
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h9f28b8cbe09a5416+0x56
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
            27717

              libc.so.1`__fdsync+0xa
              libsqlite3.so.0.8.6`unixSync+0x27
              libsqlite3.so.0.8.6`pagerWalFrames+0x808
              libsqlite3.so.0.8.6`sqlite3PagerCommitPhaseOne.part.0+0xd6
              libsqlite3.so.0.8.6`sqlite3BtreeCommitPhaseOne.part.0+0x77
              libsqlite3.so.0.8.6`sqlite3VdbeHalt+0xe1f
              libsqlite3.so.0.8.6`sqlite3VdbeExec+0x9ef4
              libsqlite3.so.0.8.6`sqlite3_step+0x50b
              crucible-downstairs-stock`rusqlite::statement::Statement::execute_with_bound_parameters::ha3394ff9a5a5f4f7+0x20
              crucible-downstairs-stock`crucible_downstairs::region::Inner::set_flush_number::h8b5da2ebc784c069+0x554
              crucible-downstairs-stock`crucible_downstairs::region::Extent::flush::{{closure}}::hef5a6a42edc99711+0xe0b
              crucible-downstairs-stock`crucible_downstairs::region::Region::region_flush::{{closure}}::{{closure}}::{{closure}}::hee73657bd4698756+0x9a
              crucible-downstairs-stock`tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h4896c8105e86516c+0x42
              crucible-downstairs-stock`tokio::runtime::task::core::Core<T,S>::poll::hfd96b7233ec469b1+0x2d
              crucible-downstairs-stock`tokio::runtime::task::harness::Harness<T,S>::poll::h9f28b8cbe09a5416+0x56
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfbea7f0d626aff17+0x24f
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::Context::run::h0eab3b6f8447cd17+0x6bb
              crucible-downstairs-stock`tokio::runtime::context::scoped::Scoped<T>::set::h665b29acdabcee04+0x3c
              crucible-downstairs-stock`tokio::runtime::context::runtime::enter_runtime::h768abda5d98a2bbd+0xc4
              crucible-downstairs-stock`tokio::runtime::scheduler::multi_thread::worker::run::ha36880354cc15137+0x47
            27717
```

So on the write side, both syncs are a result of metadb activity; on the flush side, three of the four are metadb activity (on the flush side we additionally need to sync all data -- which indeed, is the point).  We can't eliminate these syncs entirely, but we can reduce them to one sync on the write side and two on the flush side by grouping all metadb operations into transactions. 

Each `zfs_fsync` call takes ~80-100 µsecs; this allows us to eliminate at least ~160-200 µsecs from a flush and ~80-120 µsecs from a write.

Here is a D script to explore the time spent on flushes in particular, end-to-end from the guest's perspective:

```dtrace
#pragma D option quiet

propolis*:::nvme_flush_enqueue
{
        op[arg2] = timestamp;
}

propolis*:::nvme_flush_complete
/(this->start = op[arg0]) != 0/
{
        this->delta = (timestamp - this->start) / 1000;
        @l = llquantize(this->delta, 10, 0, 6, 20);
        @a = avg(this->delta);
        op[arg0] = 0;
}

tick-1sec
{
        printa("avg  = %@d us\n", @a);
        printa("dist = %@d", @l);
}
```

Here is pasted output of this script side-by-side with the stock Crucible and a prototype that takes us to two syncs on the flush side and one on the write side:

```
avg  = 817 us	                                                        avg  = 532 us
dist = 	                                                                dist =     
           value  ------------- Distribution ------------- count    	           value  ------------- Distribution ------------- count    
              70 |                                         0        	              70 |                                         1        
              75 |                                         1        	              75 |                                         1        
              80 |                                         6        	              80 |                                         2        
              85 |                                         8        	              85 |                                         15       
              90 |                                         5        	              90 |                                         7        
              95 |                                         3        	              95 |                                         5        
             100 |                                         15       	             100 |                                         27       
             150 |                                         1        	             150 |                                         2        
             200 |                                         1        	             200 |                                         1        
             250 |                                         0        	             250 |                                         0        
             300 |                                         0        	             300 |                                         15       
             350 |                                         0        	             350 |                                         1005     
             400 |                                         0        	             400 |@@                                       6976     
             450 |                                         0        	             450 |@@@@@@@@@@@                              34831    
             500 |                                         9        	             500 |@@@@@@@@@@@@                             38710    
             550 |                                         111      	             550 |@@@@@@@@                                 25193    
             600 |                                         268      	             600 |@@@                                      10439    
             650 |@                                        1387     	             650 |@                                        3989     
             700 |@@@@@@                                   8142     	             700 |@                                        1561     
             750 |@@@@@@@@@@@                              14350    	             750 |                                         649      
             800 |@@@@@@@@@                                11040    	             800 |                                         235      
             850 |@@@@@@                                   7451     	             850 |                                         116      
             900 |@@@                                      4295     	             900 |                                         60       
             950 |@@                                       1929     	             950 |                                         23       
            1000 |@                                        1640     	            1000 |                                         52       
            1500 |                                         12       	            1500 |                                         8        
            2000 |                                         5        	            2000 |                                         6        
            2500 |                                         1        	            2500 |                                         1        
            3000 |                                         1        	            3000 |                                         0        
            3500 |                                         0        	            3500 |                                         0        

```

This win is even bigger than modeled (~250+ µsecs).  This shows up in the `pgbench` results too, where the single connection result sees about a 25% win.

### PR DESCRIPTION
**Pull request by bcantrill**
Fixes #880.

### CODE REVIEW

File: downstairs/src/region.rs [hunk 1]
```diff
@@ -1426,18 +1455,25 @@ impl Extent {
...
         cdt::extent__flush__sqlite__insert__done!(|| {
             (job_id, self.number, n_dirty_blocks)
         });
 
-        // Reset the file's seek offset to 0, and set the flush number and gen
-        // number
-        inner.file.seek(SeekFrom::Start(0))?;
-
         inner.set_flush_number(new_flush, new_gen)?;
+        tx.commit()?;
```
Comment (faithanalog) [inline downstairs/src/region.rs:1473]: if this works, i don't understand why. this code is not passing the transaction into `set_flush_number()` which means the sqlite queries inside `set_flush_number()` aren't using the transaction, right? what *are* they doing? I have the same question for setting the dirty flag in `write()` further up the file.

Comment (jgallagher) [reply downstairs/src/region.rs:1473]: > Though, given I was reading that `.transaction()` returns an `&mut` to make the borrow checker statically avoid nested transactions, maybe this makes sense. Is it just the case that `Transaction` providing its own functions for getting prepared statements is to work within the limits of rust's type system, and that it doesn't actually reflect the way sqlite is used at the C-api level?

Yes, this is right. The SQLite C API doesn't have a notion of transactions at all - it just has a connection, and opening/committing/rolling back a transaction all happen via SQL statements executed on that connection. This is most obvious from rusqlite's point of view in [`Transaction::new_unchecked()`](https://docs.rs/rusqlite/0.29.0/src/rusqlite/transaction.rs.html#121-129): it executes a `BEGIN ...` and then just wraps the connection, which we are now tracking at the type system level as being in a transaction. (This can be trivially foiled by a program that executes its own `BEGIN/COMMIT/ROLLBACK` SQL that rusqlite doesn't know about.)

File: downstairs/src/region.rs [hunk 2]
```diff
@@ -1165,6 +1187,13 @@ impl Extent {
...
         }
 
+        // We do all of our metadb updates in a single transaction to minimize
+        // syncs.  (Note that the "unchecked" in the signature merely denotes
+        // that we are taking responsibility for assuring that we are not
+        // in a nested transaction, accepting that it will fail at run-time
+        // if we are.)
+        let tx = inner.metadb.unchecked_transaction()?;
+
         inner.set_dirty()?;
```
Comment (leftwo) [inline downstairs/src/region.rs:1197]: Could we hoist the dtrace probe point just above this?

I'm also wondering about the `set_dirty()` here, and if it should come at the top as well.  I'm not sure all the failure cases of failing on the `unchecked_transaction()`, like, in the failure case, will it for sure not have dirtied something that we will need to repair?  It seems like it's okay, but missing a dirty bit setting can result in a bad repair and data corruption that could be very very hard to find, so setting that dirty bit correctly is critical.

File: downstairs/src/region.rs [hunk 3]
```diff
@@ -1165,6 +1187,13 @@ impl Extent {
             }
         }
 
+        // We do all of our metadb updates in a single transaction to minimize
+        // syncs.  (Note that the "unchecked" in the signature merely denotes
+        // that we are taking responsibility for assuring that we are not
+        // in a nested transaction, accepting that it will fail at run-time
+        // if we are.)
+        let tx = inner.metadb.unchecked_transaction()?;
```
Comment (jmpesp) [inline downstairs/src/region.rs:1195]: Moving this statement before `set_dirty` is suspect, like others have pointed out, but beyond that I don't understand why moving this statement (or the others in this PR) increases performance at all.

Is it that using `unchecked_transaction` is faster than `transaction`? Does the statement movement have to occur, or is the switch to `unchecked_transaction` that helps?

File: downstairs/src/region.rs [hunk 4]
```diff
@@ -1426,18 +1455,25 @@ impl Extent {
...
 
-        // Reset the file's seek offset to 0, and set the flush number and gen
-        // number
-        inner.file.seek(SeekFrom::Start(0))?;
-
         inner.set_flush_number(new_flush, new_gen)?;
+        tx.commit()?;
+
+        // Finally, reset the file's seek offset to 0
+        inner.file.seek(SeekFrom::Start(0))?;
```
Comment (jmpesp) [inline downstairs/src/region.rs:1476]: Incidentally, does this need to occur?

File: downstairs/src/region.rs (hunk 2 above)
Comment (bcantrill) [reply downstairs/src/region.rs:1197]: On the DTrace probe: which one do you want to hoist?  (Note that this change isn't changing the `set_dirty` with respect to the existing `extent-write-sqlite-insert-start` probe.)

File: downstairs/src/region.rs (hunk 3 above)
Comment (jmpesp) [reply downstairs/src/region.rs:1195]: > When the metadb operations are grouped into a transaction, there is a single sync on the commit of the transaction; when they are not in a transaction, every update induces a sync

I get that part, and after rereading my comment think that my question was not getting at my my lack of understanding properly: it doesn't look like moving that statement **should** help, as @faithanalog pointed out: `set_dirty` doesn't accept `tx` as a parameter and use it.

Reading @jgallagher's comment makes this make more sense to me:

> The SQLite C API doesn't have a notion of transactions at all - it just has a connection, and opening/committing/rolling back a transaction all happen via SQL statements executed on that connection.

File: downstairs/src/region.rs (hunk 1 above)
Comment (jgallagher) [reply downstairs/src/region.rs:1473]: An idle thought looking at `Transaction::new_unchecked()` again (and remembering #436 go by): it calls [`conn.execute_batch("BEGIN ...")`](https://docs.rs/rusqlite/0.29.0/src/rusqlite/transaction.rs.html#126) which internally calls [`conn.prepare(...)`](https://docs.rs/rusqlite/0.29.0/src/rusqlite/lib.rs.html#501), _not_ `conn.prepare_cached()`. So every transaction opened (and committed, which uses the same mechanism) incurs a new statement preparation. I don't know whether that has a material perf impact but wanted to mention it.

File: downstairs/src/region.rs (hunk 2 above)
Comment (jgallagher) [reply downstairs/src/region.rs:1197]: >

File: downstairs/src/region.rs (hunk 3 above)
Comment (jmpesp) [reply downstairs/src/region.rs:1195]: We should change those inner functions to accept `tx` as a parameter - if not in this PR there should be a follow up issue.

File: downstairs/src/region.rs (hunk 2 above)
Comment (jgallagher) [reply downstairs/src/region.rs:1197]: > So, per the block comment immediately above it, `unchecked_transaction` is a bit poorly named. The reason it will fail is due to programmer error (and I honestly wish that this wouldn't fail but would instead `panic` on failure); the failure case isn't something that we would expect.

You could do this yourself (i.e., check for the "nested transaction" error and panic), but it's super awkward. Opening a transaction executes a SQL statement so can (at the API level) fail for any reason any SQL execution could fail, and the failure on nested transactions specifically does not have its own error code:

```
SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("cannot start a transaction within a transaction"))
```

`extended_code: 1` is [`SQLITE_ERROR`](https://www.sqlite.org/rescode.html#error):

> The SQLITE_ERROR result code is a generic error code that is used when no other more specific error code is available.

which means you'd have to check the error string (which itself is coming from sqlite) :nauseated_face:

File: downstairs/src/region.rs (hunk 3 above)
Comment (jgallagher) [reply downstairs/src/region.rs:1195]: > Is it that using `unchecked_transaction` is faster than `transaction`?

It's definitely not faster: `transaction` is [just a call to `unchecked_transaction`](https://docs.rs/rusqlite/0.29.0/src/rusqlite/transaction.rs.html#107-109); the difference is in the lifetime on the connection. `transaction()` requires a `&mut Connection` (thus ensuring there are no other open `Transaction`s on this same connection statically, assuming no funny business on the connection that rusqlite doesn't know about), whereas `unchecked_transaction()` accepts `&Connection` (which will allow programs to compile that open nested transactions, which will then fail at runtime).

File: downstairs/src/region.rs (hunk 2 above)
Comment (leftwo) [reply downstairs/src/region.rs:1197]: Ah, live discussion had informed me, and I think we are good to go like this was.

**Review by leftwo — APPROVED** [review]

File: downstairs/src/region.rs (hunk 3 above)
Comment (jmpesp) [reply downstairs/src/region.rs:1195]: I'll paste what I said in a meeting: alternatively, we should remove `tx` as a parameter, if it's not necessary, and explain that we're using sqlite transactions without needing to worry about `rusqlite::Transaction`.

**Review by jmpesp — APPROVED** [review]
