### PR TITLE
Wait for ZFS snapshot directory + agent fixes

### LINKED ISSUE #827: Snapshots don't instantly mount in the dataset's `.zfs/snapshot` directory
When creating a snapshot during the finalizing an image upload, the pantry had a requested snapshot:

	18:07:26.653Z INFO crucible-pantry (dropshot): accepted connection
	    local_addr = [fd00:1122:3344:102::5]:17000
	    remote_addr = [fd00:1122:3344:101::4]:35744
	18:07:26.654Z INFO crucible: flush with snap requested
	18:07:26.716Z INFO crucible-pantry (dropshot): request completed
	    local_addr = [fd00:1122:3344:102::5]:17000
	    method = POST
	    remote_addr = [fd00:1122:3344:101::4]:35744
	    req_id = 51bbc8b7-5c84-4319-a9ec-6fbb4208efa4
	    response_code = 204
	    uri = /crucible/pantry/0/volume/c0a6042a-6c60-4e69-872c-951a06778f44/snapshot

The next step of the snapshot create saga is to validate that those snapshots exist, and create running snapshots out of those. However, here's the agent saying that the snapshot doesn't exist:

	18:07:26.888Z INFO crucible-agent (datafile): checking if path "/data/regions/f7d172bf-3c56-4aa5-a0ff-8057c720ca76/.zfs/snapshot" exists
	18:07:26.888Z INFO crucible-agent (datafile): checking path "/data/regions/f7d172bf-3c56-4aa5-a0ff-8057c720ca76/.zfs/snapshot"
	18:07:26.888Z INFO crucible-agent (dropshot): request completed
	    error_message_external = Not Found
	    error_message_internal = region RegionId("f7d172bf-3c56-4aa5-a0ff-8057c720ca76") snapshot "4d8bc95c-a82d-4942-b7ff-d21a7518afa8" not found
	    local_addr = [fd00:1122:3344:102::7]:32345
	    method = GET
	    remote_addr = [fd00:1122:3344:101::4]:53379
	    req_id = 23fcdea4-dfc8-44e5-a115-33d30f2c03c9
	    response_code = 404
	    uri = /crucible/0/regions/f7d172bf-3c56-4aa5-a0ff-8057c720ca76/snapshots/4d8bc95c-a82d-4942-b7ff-d21a7518afa8

Checking later, It does though:

	root@oxz_crucible_oxp_4ac23275-d8fc-e984-b72c-a5d148ffde7c:~# ls /data/regions/f7d172bf-3c56-4aa5-a0ff-8057c720ca76/.zfs/snapshot
4d8bc95c-a82d-4942-b7ff-d21a7518afa8

This caused the snapshot-create saga to fail, and the unwind fails too because it can't clean up a snapshot that isn't there. It seems like 172ms isn't long enough to wait for a snapshot to be mounted in the dataset's directory.

### PR DESCRIPTION
**Pull request by jmpesp**
When `zfs snapshot dataset@name` is called, the ZFS snapshot is not instantaneously mounted to the appropriate .../.zfs/snapshot/<name> path (as long as 172 ms was measured for a zpool with file backed vdevs). There's two fixes that result from this:

1. Use `zfs list -t snapshot ...` to tell if a snapshot exists, not the presence of the mounted snapshot directory

2. Wait for the ZFS snapshot directory to get mounted before starting a read-only downstairs service that points to it. Wait a maximum of 5 seconds before returning an error.

Also bundled in this commit is a fix for an agent bug: it's possible for a snapshot to have a running read-only downstairs that is in the destroyed state (but not deleted yet), and this will prevent the deletion of said snapshot, as the deletion code simply checked for the presence of a running read-only snapshot and not its state. Fix this by matching on the state and allowing deletion.

Also (!) bundled in this commit is another fix for another agent bug: when getting snapshots for a region, if the region wasn't in state Created then the endpoint would return 500. This is wrong, and we can handle more states than !Created. The only state that should return 500 is Failed.

Fixes #827.

### CODE REVIEW

File: agent/src/datafile.rs [hunk 1]
```diff
@@ -341,17 +374,26 @@ impl DataFile {
...
+                match running_snapshot.state {
+                    State::Requested | State::Created | State::Tombstoned => {
+                        bail!(
+                            "read-only downstairs running for region {} snapshot {}",
+                            request.id.0,
+                            request.name
+                        );
+                    }
+
+                    State::Destroyed | State::Failed => {
```
Comment (leftwo) [inline agent/src/datafile.rs:393]: Which state here are we looking at?  The state of a downstairs somewhere?

If the state is failed, could it be failed and then come back later and not be failed and then want this snapshot?

File: agent/src/datafile.rs [hunk 2]
```diff
@@ -714,106 +756,93 @@ impl DataFile {
...
+            .arg("-o")
+            .arg("name")
+            .arg("-r")
+            .arg(dataset.dataset())
+            .output()?;
 
-                    // Remove newline
-                    let cmd_stdout = cmd_stdout.trim_end().to_string();
+        if !cmd.status.success() {
+            bail!("zfs list snapshots failed!");
```
Comment (leftwo) [inline agent/src/datafile.rs:799]: Do we want to print out the error here if we saw one?

File: agent/src/datafile.rs [hunk 3]
```diff
@@ -714,106 +756,93 @@ impl DataFile {
...
+        for snapshot in snapshots_list {
+            if snapshot == dataset.dataset() {
+                info!(self.log, "skipping {} matches dataset name", snapshot);
+                continue;
+            }
+            info!(self.log, "snapshot is {}", &snapshot);
+            let parts: Vec<&str> = snapshot.split('@').collect();
+            info!(self.log, "parts is {:?}", &parts);
+            if parts.len() != 2 {
+                panic!("bad snapshot name");
```
Comment (leftwo) [inline agent/src/datafile.rs:820]: When would we hit this panic?   I worry that some output from the zfs command we don't expect would cause us to panic here, and that would be sad :(

File: agent/src/datafile.rs [hunk 4]
```diff
@@ -714,106 +756,93 @@ impl DataFile {
...
+
+            let cmd = Command::new("zfs")
+                .arg("get")
+                .arg("-pH")
+                .arg("-o")
+                .arg("value")
+                .arg("creation")
+                .arg(snapshot)
+                .output()?;
+
```
Comment (leftwo) [inline agent/src/datafile.rs:832]: Do we need a `if !cmd.status.success() {` check here?  Or if we fail, does cmd_stdout just end up
with nothing in it?

**Review by leftwo — COMMENTED** [review]
Some questions for you

File: agent/src/datafile.rs (hunk 1 above)
Comment (jmpesp) [reply agent/src/datafile.rs:393]: This is the stored state for a "running snapshot" (aka read only downstairs booted at the snapshot's mount dir: I like and don't like the "running snapshot" name but here we are).

As far as I can tell, there's no path in the `state` state machine to transition out of `Failed` for any of the resources that the agent can interact with.

File: agent/src/datafile.rs (hunk 2 above)
Comment (jmpesp) [reply agent/src/datafile.rs:810]: yes definitely, done in dfb1358

File: agent/src/datafile.rs (hunk 4 above)
Comment (jmpesp) [reply agent/src/datafile.rs:845]: Error check added in dfb1358
